---

- hosts: all
  become: false

  tasks:
  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: Install apache package
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: Add PHP support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest