---

- hosts: all
  become: false

  tasks:
  - name: Remove apache package
    ansible.builtin.apt:
      name: apache2
      state: absent

  - name: Remove PHP support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent